Create a new branch for fast forward
istio/test-infra pull request #155
Opened 2017-03-31 23:40 UTC by yutongz

https://github.com/istio/istio-testing/issues/113

2017-04-01 00:03 UTC, istio-testing commented
Jenkins job istio-testing/pr-master passed

2017-04-01 05:54 UTC, sebastienvas commented on tools/github_helper/main.go
> +	for true {
please use something like fastfoward-SHORTSHA

2017-04-01 05:57 UTC, istio-testing commented
This is a test.

2017-04-01 05:57 UTC, istio-testing commented
Jenkins job istio-testing/pr-master passed

2017-04-01 14:53 UTC, sebastienvas requested changes
PTAL

2017-04-02 22:30 UTC, istio-testing commented
This is a test.

2017-04-02 22:31 UTC, istio-testing commented
Jenkins job istio-testing/pr-master passed

2017-04-03 16:19 UTC, sebastienvas commented on tools/github_helper/main.go
> +	branchName := fmt.Sprintf("fastForward-%s", (*commit)[0:7])
Can we do something like fastForward/${headBranch ie master}-GIT_SHORT_SHA.

2017-04-03 16:22 UTC, sebastienvas commented on tools/github_helper/main.go
> +func (h helper) createBranchForFastForward(commit *string) error {
Please pass the branch name as an argument. And generate it in createPullRequestToBase to avoid code duplication

2017-04-03 16:22 UTC, sebastienvas commented on tools/github_helper/main.go
> +	if err := h.createBranchForFastForward(commit); err != nil {
Move that logging to createBranchForFastForward

2017-04-03 16:23 UTC, sebastienvas commented on tools/github_helper/main.go
> +	log.Printf("Created a new branch for fast forward: %s", newHead)
Move that logging to createBranchForFastForward

2017-04-03 16:24 UTC, sebastienvas commented on tools/github_helper/main.go
> +	if err := h.createBranchForFastForward(commit); err != nil {
We should probably check if the branch already exists and return nil in that case.

2017-04-03 16:28 UTC, sebastienvas requested changes
PTAL

2017-04-03 18:59 UTC, istio-testing commented
This is a test.

2017-04-03 19:00 UTC, istio-testing commented
Jenkins job istio-testing/pr-master passed

2017-04-03 19:04 UTC, yutongz commented on tools/github_helper/main.go
> +	branchName := fmt.Sprintf("fastForward-%s", (*commit)[0:7])
It turns out we can't use "/" in branch name

2017-04-03 20:48 UTC, sebastienvas commented on tools/github_helper/main.go
> +	if refer, resp, err := h.Client.Git.GetRef(context.TODO(), h.Owner, h.Repo, ref); resp.StatusCode != 404 {
I don t think you need to actually get the ref, you can just look at the reponse from CreateRef.

2017-04-03 20:50 UTC, sebastienvas approved these changes
Minor changes.

2017-04-03 22:35 UTC, istio-testing commented
This is a test.

2017-04-03 22:35 UTC, istio-testing commented
Jenkins job istio-testing/pr-master passed

2017-04-04 21:27 UTC, merged