Add flag to skip cla/codecov failure in fast forward
istio/test-infra pull request #159
Opened 2017-04-06 20:26 UTC by yutongz

https://github.com/istio/istio-testing/issues/157

2017-04-06 20:31 UTC, istio-testing commented
This is a test.

2017-04-06 20:31 UTC, istio-testing commented
Jenkins job istio-testing/pr-master passed

2017-04-07 21:01 UTC, sebastienvas requested changes
PLease create a unique flag.

2017-04-07 21:01 UTC, sebastienvas commented on tools/github_helper/main.go
> +	codecov     = flag.Bool("codecov", false, "Skip code coverage failure")
Please create a unique flag for those that takes in a comma separated list of context to skip.

2017-04-07 21:01 UTC, sebastienvas commented on tools/github_helper/main.go
> +	Codecov bool
Change this with something like ChecksToSkip

2017-04-10 07:16 UTC, istio-testing commented
This is a test.

2017-04-10 07:16 UTC, istio-testing commented
Jenkins job istio-testing/presubmit passed

2017-04-10 20:28 UTC, sebastienvas reviewed
Just a minor comment

2017-04-10 20:28 UTC, sebastienvas commented on tools/github_helper/main.go
> +					if *status.Context == check {
Have you tried this ? Should we use some kind of regex instead ?

2017-04-10 22:56 UTC, yutongz commented on tools/github_helper/main.go
> +					if *status.Context == check {
I tested its logic by creating a fake combinedStatus directly in the updatePullRequest(), working but naive.
And does this pattern work for you:
keyWord := "cla"   //input flag
pattern := fmt.Sprintf("(^|/)%s(/|$)", keyWord)

2017-04-10 23:58 UTC, sebastienvas commented on tools/github_helper/main.go
> +					if *status.Context == check {
what about fmt.Sprintf("*%s.*", keyWord) ?

2017-04-11 04:09 UTC, yutongz commented on tools/github_helper/main.go
> +					if *status.Context == check {
Well, I think it depends on what possible contexts we have. Are we going to have some confused cases. But in this situation, I think we may prefer false negative to false positive. If we can skip one check while the program block it, well, it's easy to manually check and pass it. On contrary, we may miss a really failure.

2017-04-11 04:48 UTC, sebastienvas submitted a review, later dismissed

2017-04-11 04:50 UTC, istio-testing commented
This is a test.

2017-04-11 04:51 UTC, istio-testing commented
Jenkins job istio-testing/presubmit passed

2017-04-11 05:26 UTC, istio-testing commented
This is a test.

2017-04-11 05:27 UTC, istio-testing commented
Jenkins job istio-testing/presubmit passed

2017-04-11 05:30 UTC, istio-testing commented
This is a test.

2017-04-11 05:31 UTC, istio-testing commented
Jenkins job istio-testing/presubmit passed

2017-04-11 18:24 UTC, istio-testing commented
This is a test.

2017-04-11 18:24 UTC, istio-testing commented
Jenkins job istio-testing/presubmit passed

2017-04-11 18:32 UTC, sebastienvas commented
To plug it to Jenkins, please update the following to take a build parameters for exceptions 
https://github.com/istio/istio-testing/blob/master/src/org/istio/testutils/Utilities.groovy#L99
And update https://testing.istio.io/job/istio-testing/job/verify-stable-prs/

2017-04-11 21:26 UTC, istio-testing commented
This is a test.

2017-04-11 21:26 UTC, istio-testing commented
Jenkins job istio-testing/presubmit passed

2017-04-11 21:41 UTC, istio-testing commented
This is a test.

2017-04-11 21:42 UTC, istio-testing commented
Jenkins job istio-testing/presubmit passed

2017-04-11 21:42 UTC, yutongz commented
PTAL

2017-04-11 22:50 UTC, sebastienvas approved these changes
Awesome

2017-04-11 22:51 UTC, merged