Enable tide for CNI
istio/test-infra pull request #1669
Opened 2019-08-14 16:28 UTC by howardjohn

2019-08-14 16:31 UTC, geeknoid approved these changes

2019-08-15 22:12 UTC, clarketm requested changes

2019-08-15 22:12 UTC, clarketm commented on prow/config.yaml
> +          required_pull_request_reviews: *tide_withcodeowners_reviews
```suggestion

```

Now that #1666 has merged , the `tide_withcodeowners_reviews` and `tide_withcodeowners_restrictions` anchors are no longer defined.

2019-08-15 22:12 UTC, clarketm commented on prow/config.yaml
> +          restrictions: *tide_withcodeowners_restrictions
```suggestion

```

2019-08-15 22:18 UTC, clarketm commented on prow/config.yaml
> +          required_pull_request_reviews: *tide_withcodeowners_reviews
Otherwise, there may be unintentional conflicts or reversions.

2019-08-16 16:07 UTC, howardjohn commented
Thanks @clarketm , should be fixed now

2019-08-16 16:09 UTC, geeknoid approved these changes

2019-08-16 16:12 UTC, clarketm approved these changes

2019-08-16 16:17 UTC, merged

2019-08-16 16:17 UTC, istio-testing commented
@howardjohn: Updated the following 2 configmaps:
 * `config` configmap in namespace `default` using the following files:
   - key `config.yaml` using file `prow/config.yaml`
 * `job-config` configmap in namespace `default` using the following files:
   - key `istio.cni.master.yaml` using file `prow/cluster/jobs/istio/cni/istio.cni.master.yaml`
   - key `istio.cni.release-1.3.yaml` using file `prow/cluster/jobs/istio/cni/istio.cni.release-1.3.yaml`


<details>

In response to [this](https://github.com/istio/test-infra/pull/1669):

>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>