Add benchmark to periodic job
istio/test-infra pull request #1909
Opened 2019-10-08 22:48 UTC by richardwxn

2019-10-09 18:21 UTC, howardjohn requested changes

2019-10-09 18:21 UTC, howardjohn commented on prow/cluster/jobs/all-periodics.yaml
> +          - scripts/get_tools_repo.sh
get_tools_repo depends on artifacts of the daily build. We can probably just directly clone. I suggest removing this line and adding:
```
    extra_refs:
   - org: istio
      repo: tools
     base_ref: master
      path_alias: istio.io/tools
```

2019-10-09 18:21 UTC, howardjohn commented on prow/cluster/jobs/all-periodics.yaml
> +          - scripts/run-test.sh
this also depends on the artifacts. You can find the latest build at https://storage.googleapis.com/istio-build/dev/latest which points to the last merged commit here: https://gcsweb.istio.io/gcs/istio-build/dev/

2019-10-09 20:29 UTC, richardwxn commented on prow/cluster/jobs/all-periodics.yaml
> +          - scripts/get_tools_repo.sh
thanks for pointing out. Seems like get_tools_repo and run_tests both depend on the SHA from the daily build manifests file? Looking at your suggestion, is adding ref to master of istio.io/istio and istio.io/tools enough or we need to depend on the SHA from here: https://storage.googleapis.com/istio-build/dev/latest?

2019-10-09 20:37 UTC, howardjohn commented on prow/cluster/jobs/all-periodics.yaml
> +          - scripts/get_tools_repo.sh
I think we can run tools from master, but we want to test and record info about a specific PR, so fetching the SHA seems better. But really it should be the same.. master is going to be the same one pointed to by the dev/latest. If you do master you may hit a race though where its been merged but not yet published

2019-10-09 20:40 UTC, howardjohn reviewed
From https://github.com/istio/tools/blob/e97b1eb7981216a5c4741314feadf76acc41a1a3/perf/benchmark/run_benchmark_job.sh#L66 looks like we need to get $TAG from somewhere. I suggest from the dev/latest. But we also need to make the `setup_istio` support pulling from there. I think that should be pretty simple though, just adding a new GCS url

2019-10-09 23:15 UTC, richardwxn commented
is it good to go after https://github.com/istio/tools/pull/432 and https://github.com/istio/tools/pull/433 merged?

2019-10-13 17:52 UTC, howardjohn approved these changes

2019-10-13 17:57 UTC, merged

2019-10-13 17:57 UTC, istio-testing commented
@richardwxn: Updated the `job-config` configmap in namespace `default` using the following files:
 - key `all-periodics.yaml` using file `prow/cluster/jobs/all-periodics.yaml`

<details>

In response to [this](https://github.com/istio/test-infra/pull/1909):

>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>