common-files update master-2019-12-15T16-17-48
istio/test-infra pull request #2228
Opened 2019-12-17 23:47 UTC by sdake

Update to common-files with image master-2019-12-15T16-17-48

2019-12-17 23:47 UTC, istio-testing commented
@sdake: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2019-12-17 23:48 UTC, istio-testing commented
@sdake: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_test-infra | 943ec5b4b1f93907516f3ec54036498cf3807aeb | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2228/lint_test-infra/994) | `/test lint_test-infra`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-12-17 23:48 UTC, istio-testing commented
@sdake: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_test-infra | 943ec5b4b1f93907516f3ec54036498cf3807aeb | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2228/lint_test-infra/994) | `/test lint_test-infra`
test_test-infra | 943ec5b4b1f93907516f3ec54036498cf3807aeb | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2228/test_test-infra/999) | `/test test_test-infra`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-12-17 23:48 UTC, istio-testing commented
@sdake: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_test-infra | 943ec5b4b1f93907516f3ec54036498cf3807aeb | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2228/lint_test-infra/994) | `/test lint_test-infra`
test_test-infra | 943ec5b4b1f93907516f3ec54036498cf3807aeb | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2228/test_test-infra/999) | `/test test_test-infra`
pull-test-infra-prow-checkconfig | 943ec5b4b1f93907516f3ec54036498cf3807aeb | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2228/pull-test-infra-prow-checkconfig/3319) | `/test pull-test-infra-prow-checkconfig`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-12-17 23:48 UTC, istio-testing commented
@sdake: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_test-infra | 943ec5b4b1f93907516f3ec54036498cf3807aeb | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2228/lint_test-infra/994) | `/test lint_test-infra`
test_test-infra | 943ec5b4b1f93907516f3ec54036498cf3807aeb | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2228/test_test-infra/999) | `/test test_test-infra`
pull-test-infra-prow-checkconfig | 943ec5b4b1f93907516f3ec54036498cf3807aeb | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2228/pull-test-infra-prow-checkconfig/3319) | `/test pull-test-infra-prow-checkconfig`
pull-test-infra-check-testgrid-config | 943ec5b4b1f93907516f3ec54036498cf3807aeb | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2228/pull-test-infra-check-testgrid-config/54) | `/test pull-test-infra-check-testgrid-config`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-12-17 23:48 UTC, istio-testing commented
@sdake: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_test-infra | 943ec5b4b1f93907516f3ec54036498cf3807aeb | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2228/lint_test-infra/994) | `/test lint_test-infra`
test_test-infra | 943ec5b4b1f93907516f3ec54036498cf3807aeb | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2228/test_test-infra/999) | `/test test_test-infra`
pull-test-infra-prow-checkconfig | 943ec5b4b1f93907516f3ec54036498cf3807aeb | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2228/pull-test-infra-prow-checkconfig/3319) | `/test pull-test-infra-prow-checkconfig`
pull-test-infra-check-testgrid-config | 943ec5b4b1f93907516f3ec54036498cf3807aeb | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2228/pull-test-infra-check-testgrid-config/54) | `/test pull-test-infra-check-testgrid-config`
prow: flakey-run | 943ec5b4b1f93907516f3ec54036498cf3807aeb | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2228/flakey-run/89) | `/test flakey-run`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-12-17 23:48 UTC, istio-testing commented
@sdake: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_test-infra | 943ec5b4b1f93907516f3ec54036498cf3807aeb | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2228/lint_test-infra/994) | `/test lint_test-infra`
test_test-infra | 943ec5b4b1f93907516f3ec54036498cf3807aeb | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2228/test_test-infra/999) | `/test test_test-infra`
pull-test-infra-prow-checkconfig | 943ec5b4b1f93907516f3ec54036498cf3807aeb | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2228/pull-test-infra-prow-checkconfig/3319) | `/test pull-test-infra-prow-checkconfig`
pull-test-infra-check-testgrid-config | 943ec5b4b1f93907516f3ec54036498cf3807aeb | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2228/pull-test-infra-check-testgrid-config/54) | `/test pull-test-infra-check-testgrid-config`
prow: flakey-run | 943ec5b4b1f93907516f3ec54036498cf3807aeb | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2228/flakey-run/89) | `/test flakey-run`
gencheck_test-infra | 943ec5b4b1f93907516f3ec54036498cf3807aeb | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2228/gencheck_test-infra/850) | `/test gencheck_test-infra`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-12-17 23:56 UTC, howardjohn requested changes
somethign went wrong here

2019-12-18 00:04 UTC, closed without merging

2019-12-18 00:05 UTC, sdake commented
@clarketm fyi - this was a result of running the automation I handed off to you. Just thought you should see it.

I am not sure what the root cause is - possibly a change in my local branch of test-infra on master.

Cheers
-steve

2019-12-18 00:14 UTC, clarketm commented
Thanks for the info. FWIW, in the job that I created (adapted from your script) it will perform a fresh, shallow clone of the destination repo as when testing this issue did not occur (ref: https://github.com/istio/test-infra/pull/2223), so I think is may be an issue with the local repo source.