Metrics fetcher for jenkins and code coverage
istio/test-infra pull request #252
Opened 2017-06-21 23:18 UTC by yutongz

2017-06-21 23:21 UTC, istio-testing commented
This is a test.

2017-06-21 23:21 UTC, istio-testing commented
Jenkins job test-infra/presubmit passed

2017-06-21 23:21 UTC, istio-testing commented
This is a test.

2017-06-21 23:21 UTC, istio-testing commented
Jenkins job test-infra/presubmit passed

2017-06-21 23:28 UTC, sebastienvas commented on toolbox/metrics/BUILD
> +        "-linkmode",
Do you know what are those for ?

2017-06-21 23:30 UTC, sebastienvas commented on toolbox/metrics/main.go
> +	codeCovTrackJob = "presubmit"
Dont you want to use postsubmit here ? Or actually fastforward job ? presubmit might not get in.

2017-06-21 23:34 UTC, sebastienvas commented on toolbox/metrics/main.go
> +	for n := range jobRegister[name] {
what if name is not in the map, would 'nt you get a nil ?

2017-06-21 23:40 UTC, sebastienvas commented on toolbox/metrics/main.go
> +	jobRegister = map[string][]string{
Can we create this list dynamically ? Does the API allow job listing ?

2017-06-21 23:43 UTC, sebastienvas commented on toolbox/metrics/main.go
> +	codeCovRegister = map[string]bool{
Same comment here, Can we attempt to get code coverage on all the repos and just print 0 on others ?

2017-06-21 23:46 UTC, sebastienvas commented on toolbox/metrics/main.go
> +		return 0, errors.New("get empty result from jenkins")
got empty results ...

2017-06-21 23:53 UTC, yutongz commented on toolbox/metrics/main.go
> +	for n := range jobRegister[name] {
yes, we get a nil if the key doesn't exist, and when n == nil, it won't go into the loop

2017-06-22 00:02 UTC, sebastienvas requested changes
PTAL

2017-06-23 17:08 UTC, yutongz commented on toolbox/metrics/main.go
> +	codeCovTrackJob = "presubmit"
let me use postsubmit for now.

2017-06-23 17:09 UTC, yutongz commented on toolbox/metrics/BUILD
> +        "-linkmode",
static build is required for building docker image

2017-06-23 17:09 UTC, yutongz commented
PTAL

2017-06-23 17:09 UTC, istio-testing commented
This is a test.

2017-06-23 17:10 UTC, istio-testing commented
Jenkins job test-infra/presubmit passed

2017-06-23 17:44 UTC, sebastienvas commented on toolbox/metrics/main.go
> +	codeCovTrackJob = "postsubmit"
I would make this configurable.

2017-06-23 20:26 UTC, sebastienvas commented on toolbox/metrics/main.go
> +	succeededBuilds = prometheus.NewSummaryVec(
I feel this should go into a struct

2017-06-23 20:26 UTC, sebastienvas commented on toolbox/metrics/main.go
> +	jk = &jkConst{
Can you just declare those as const ?

2017-06-24 00:16 UTC, yutongz commented on toolbox/metrics/main.go
> +	jk = &jkConst{
Honestly, I prefer this way. In my point of view, these strings are from JSON files of Jenkins, so better put them into a structure.

2017-06-24 00:20 UTC, istio-testing commented
This is a test.

2017-06-24 00:20 UTC, istio-testing commented
Jenkins job test-infra/presubmit passed

2017-06-24 04:27 UTC, yutongz commented
PTAL

2017-06-26 21:21 UTC, sebastienvas commented on toolbox/metrics/main.go
> +		resultSUCCESS:      "SUCCESS",
rename to resultSuccess for consistency.

2017-06-26 21:22 UTC, sebastienvas commented on toolbox/metrics/main.go
> +	jk = &jkConst{
Golang does not support const struct which makes it ugly to declare a struct to put in const in.

2017-06-26 21:24 UTC, sebastienvas approved these changes

2017-06-29 18:25 UTC, istio-testing commented
This is a test.

2017-06-29 18:25 UTC, istio-testing commented
Jenkins job test-infra/presubmit passed

2017-07-10 21:40 UTC, istio-testing commented
This is a test.

2017-07-10 21:40 UTC, istio-testing commented
Jenkins job test-infra/presubmit passed

2017-07-10 23:40 UTC, merged