Create tmp dir for go test
istio/test-infra pull request #254
Opened 2017-07-06 18:39 UTC by yutongz

Didn't create tmp dir so that it failed to create test files

2017-07-06 18:41 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 8d3fcc7a89b11d2565449fcbec0b8e1f08cf7e29 | [link](https://indigo-almanac-168816.appspot.com/build/istio-prow/pr-logs/pull/istio_test-infra/254/test-infra-presubmit/883032709079764992/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 18:42 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 6932d6dc1aa6ab27112c40df5f7a500a4848da96 | [link](https://indigo-almanac-168816.appspot.com/build/istio-prow/pr-logs/pull/istio_test-infra/254/test-infra-presubmit/883033338212782080/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 18:44 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 6932d6dc1aa6ab27112c40df5f7a500a4848da96 | [link](https://indigo-almanac-168816.appspot.com/build/istio-prow/pr-logs/pull/istio_test-infra/254/test-infra-presubmit/883033589912965120/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 18:45 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 6932d6dc1aa6ab27112c40df5f7a500a4848da96 | [link](https://indigo-almanac-168816.appspot.com/build/istio-prow/pr-logs/pull/istio_test-infra/254/test-infra-presubmit/883034093267193856/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 18:46 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 6932d6dc1aa6ab27112c40df5f7a500a4848da96 | [link](https://indigo-almanac-168816.appspot.com/build/istio-prow/pr-logs/pull/istio_test-infra/254/test-infra-presubmit/883034344971571200/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 18:47 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 6932d6dc1aa6ab27112c40df5f7a500a4848da96 | [link](https://indigo-almanac-168816.appspot.com/build/istio-prow/pr-logs/pull/istio_test-infra/254/test-infra-presubmit/883034596562702336/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 18:48 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 6932d6dc1aa6ab27112c40df5f7a500a4848da96 | [link](https://indigo-almanac-168816.appspot.com/build/istio-prow/pr-logs/pull/istio_test-infra/254/test-infra-presubmit/883034848204165120/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 18:49 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 6932d6dc1aa6ab27112c40df5f7a500a4848da96 | [link](https://indigo-almanac-168816.appspot.com/build/istio-prow/pr-logs/pull/istio_test-infra/254/test-infra-presubmit/883035099866599424/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 18:50 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 6932d6dc1aa6ab27112c40df5f7a500a4848da96 | [link](https://indigo-almanac-168816.appspot.com/build/istio-prow/pr-logs/pull/istio_test-infra/254/test-infra-presubmit/883035351562588160/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 18:51 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 6932d6dc1aa6ab27112c40df5f7a500a4848da96 | [link](https://indigo-almanac-168816.appspot.com/build/istio-prow/pr-logs/pull/istio_test-infra/254/test-infra-presubmit/883035603149524992/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 18:52 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 6932d6dc1aa6ab27112c40df5f7a500a4848da96 | [link](https://indigo-almanac-168816.appspot.com/build/istio-prow/pr-logs/pull/istio_test-infra/254/test-infra-presubmit/883035854837125120/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 18:53 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 6932d6dc1aa6ab27112c40df5f7a500a4848da96 | [link](https://indigo-almanac-168816.appspot.com/build/istio-prow/pr-logs/pull/istio_test-infra/254/test-infra-presubmit/883036106503753728/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 18:54 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 6932d6dc1aa6ab27112c40df5f7a500a4848da96 | [link](https://indigo-almanac-168816.appspot.com/build/istio-prow/pr-logs/pull/istio_test-infra/254/test-infra-presubmit/883036358170382336/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 18:56 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://indigo-almanac-168816.appspot.com/build/istio-prow/pr-logs/pull/istio_test-infra/254/test-infra-presubmit/883036735619993600/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 18:57 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://indigo-almanac-168816.appspot.com/build/istio-prow/pr-logs/pull/istio_test-infra/254/test-infra-presubmit/883036987336953856/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 18:58 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://indigo-almanac-168816.appspot.com/build/istio-prow/pr-logs/pull/istio_test-infra/254/test-infra-presubmit/883037238986805248/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 18:58 UTC, istio-testing commented
This is a test.

2017-07-06 18:58 UTC, istio-testing commented
Jenkins job test-infra/presubmit passed

2017-07-06 18:59 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://indigo-almanac-168816.appspot.com/build/istio-prow/pr-logs/pull/istio_test-infra/254/test-infra-presubmit/883037490598907904/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:00 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://indigo-almanac-168816.appspot.com/build/istio-prow/pr-logs/pull/istio_test-infra/254/test-infra-presubmit/883037742290702336/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:01 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://indigo-almanac-168816.appspot.com/build/istio-prow/pr-logs/pull/istio_test-infra/254/test-infra-presubmit/883037994074771456/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:02 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://indigo-almanac-168816.appspot.com/build/istio-prow/pr-logs/pull/istio_test-infra/254/test-infra-presubmit/883038245602988032/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:03 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://indigo-almanac-168816.appspot.com/build/istio-prow/pr-logs/pull/istio_test-infra/254/test-infra-presubmit/883038497269616640/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:03 UTC, sebastienvas requested changes
PTAL

2017-07-06 19:03 UTC, sebastienvas commented on toolbox/pkg_check/main_test.go
> +	if _, err := os.Stat(tmpDir); os.IsNotExist(err) {
You might want to use https://golang.org/pkg/io/ioutil/#TempFile to make your test more predictable. As of now if I run your test concurrently they will fail. You want to make sure that each file name is unique.

2017-07-06 19:04 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://indigo-almanac-168816.appspot.com/build/istio-prow/pr-logs/pull/istio_test-infra/254/test-infra-presubmit/883038748940439552/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:06 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://indigo-almanac-168816.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883039163551584256/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:07 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883039514384142336/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:08 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883039766088519680/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:09 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883040017729982464/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:10 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883040269442748416/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:11 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883040521054851072/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:12 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883040772725673984/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:13 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883041024434245632/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:14 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883041276029571072/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:15 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883041527687811072/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:16 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883041779354439680/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:17 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883042031016873984/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:18 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883042282696085504/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:19 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883042534337548288/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:20 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883042785991593984/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:21 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883043037616279552/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:22 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883043289308073984/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:23 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883043540978896896/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:24 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883043792620359680/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:25 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883044044286988288/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:26 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883044295941033984/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:27 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883044547607662592/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:28 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883044799232348160/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:29 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883045050924142592/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:30 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883045302578188288/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:31 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883045554244816896/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:32 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883045805911445504/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:33 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883046057552908288/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:34 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883046309219536896/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:35 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883046560835833856/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:36 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883046812544405504/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:37 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883047064194256896/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:38 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883047315865079808/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:39 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883047567514931200/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:40 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883047819168976896/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:41 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883048070848188416/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:42 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883048322464485376/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:43 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883048574156279808/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:44 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883048825801936896/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:45 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883049077464371200/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:46 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883049329122611200/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:47 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883049580780851200/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:48 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883049832464257024/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:49 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883050084063776768/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:50 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883050335759765504/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:51 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883050587418005504/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:52 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883050839080439808/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:53 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883051090742874112/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:54 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883051342396919808/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:55 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883051594055159808/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:56 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883051845688233984/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:57 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883052097384222720/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:58 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883052349059239936/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 19:59 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883052600696508416/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 20:00 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883052852367331328/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 20:01 UTC, istio-testing commented
@yutongz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
jobs/test-infra-presubmit.sh | 07088fac59676e9b1f890e167e9cb78922974bad | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/254/test-infra-presubmit/883053104017182720/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-06 20:36 UTC, istio-testing commented
This is a test.

2017-07-06 20:36 UTC, istio-testing commented
Jenkins job test-infra/presubmit passed

2017-07-06 23:53 UTC, yutongz commented
PTAL

2017-07-07 17:13 UTC, sebastienvas approved these changes

2017-07-07 17:19 UTC, nlandolfi commented on toolbox/pkg_check/main_test.go
> +	if err := os.RemoveAll(tmpDir); err != nil {
why move this out of a defer?

2017-07-07 19:25 UTC, yutongz commented on toolbox/pkg_check/main_test.go
> +	if err := os.RemoveAll(tmpDir); err != nil {
cause os.Exit() will end it immediately without going through defer.

2017-07-10 17:10 UTC, merged