Metrics
istio/test-infra pull request #2563
Opened 2020-04-02 06:27 UTC by scottilee

Add files required for a custom monitoring and alerting stack planned for monitoring.prow.istio.io.

Fixes #1774.

2020-04-02 06:27 UTC, istio-testing commented
Hi @scottilee. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Ftest-infra).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2020-04-02 17:35 UTC, clarketm commented
/ok-to-test

2020-04-02 17:36 UTC, istio-testing commented
@scottilee: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_test-infra | 74f6394c6c1c8e7c6afe26a6781442ef2d1dd609 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2563/lint_test-infra/2135) | `/test lint_test-infra`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-04-02 20:46 UTC, clarketm requested changes

2020-04-02 20:46 UTC, clarketm commented on prow/cluster/monitoring/BUILD.bazel
> +load("//prow:def.bzl", "BUILD_CLUSTER", "MULTI_KIND", "component", "release")
Istio is not setup for `bazel` deployments. We can safely remove this (and the other) `BUILD.bazel` files from this PR. As an alternative, we can use `kubectl` (w/ `helm` for magic strings) but that can be in a follow-up.

2020-04-02 20:46 UTC, clarketm commented on prow/cluster/monitoring/OWNERS
> +approvers:
You can omit this `OWNERS` file as ownership is already handled by [`CODEOWNERS`](https://github.com/istio/test-infra/blob/master/CODEOWNERS).

2020-04-03 03:37 UTC, istio-testing commented
@scottilee: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_test-infra | aa8ae14c8b5297d39b331fc0a2a3e699832c62c3 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2563/lint_test-infra/2143) | `/test lint_test-infra`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-04-03 03:37 UTC, scottilee commented on prow/cluster/monitoring/OWNERS
> +approvers:
Done.

2020-04-03 03:37 UTC, scottilee commented on prow/cluster/monitoring/BUILD.bazel
> +load("//prow:def.bzl", "BUILD_CLUSTER", "MULTI_KIND", "component", "release")
Done.

2020-04-03 19:35 UTC, clarketm commented
@scottilee – regarding the lint errors, can you omit the `vendor` directory and update your PR? 
Managing these dependencies and auto-deploying this can be a follow-up item.

2020-04-04 00:23 UTC, istio-testing commented
@scottilee: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_test-infra | 9e6a8d3852358fedfc60439f8768d29d7afacbaa | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2563/lint_test-infra/2155) | `/test lint_test-infra`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-04-04 09:42 UTC, clarketm approved these changes
This is awesome, thanks for the help! I will create follow-up tasks for updating the README, installing vendor deps, and setting up auto-deployment.

2020-04-04 09:42 UTC, merged