Some fixes and improvements to recreate_prow_configmaps.py
istio/test-infra pull request #2599
Opened 2020-04-19 20:57 UTC by chizhg

1. Also use `replace` to update the prow job config configmap, this can avoid downtime.
2. Add a new `--silent` flag to allow users skip the confirmation step in updating configmaps.

/cc @clarketm

2020-04-19 20:58 UTC, istio-testing commented
Hi @chizhg. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Ftest-infra).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2020-04-20 00:02 UTC, clarketm commented
/ok-to-test

2020-04-20 00:03 UTC, clarketm requested changes

2020-04-20 00:03 UTC, clarketm commented on prow/recreate_prow_configmaps.py
> +        if raw_input(prompt) != "YES":
Python3 syntax is preferred.

```suggestion
        if input(prompt) != "YES":
```

2020-04-20 01:00 UTC, chizhg commented on prow/recreate_prow_configmaps.py
> +        if raw_input(prompt) != "YES":
Done.

2020-04-20 06:01 UTC, clarketm approved these changes

2020-04-20 06:03 UTC, merged