WIP: prow: add pilot postsubmit to configuration.
istio/test-infra pull request #287
Opened 2017-07-19 18:43 UTC by nlandolfi

This introduces a `pilot-postsubmit` job.

TODO:

- [ ] Prow officially supports max_concurrency.

2017-07-19 18:49 UTC, istio-testing commented
This is a test.

2017-07-19 18:49 UTC, istio-testing commented
Jenkins job test-infra/presubmit passed

2017-07-19 18:56 UTC, nlandolfi commented
Corresponding pilot PR: https://github.com/istio/pilot/pull/940

2017-07-20 17:53 UTC, nlandolfi commented
I removed the max_concurrency for now, as discussed.

2017-07-20 17:59 UTC, istio-testing commented
This is a test.

2017-07-20 17:59 UTC, istio-testing commented
Jenkins job test-infra/presubmit passed

2017-07-20 18:24 UTC, yutongz commented
/test all [submit-queue is verifying that this PR is safe to merge]

2017-07-20 21:48 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 21:49 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 21:50 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 21:51 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 21:52 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 21:53 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 21:54 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 21:55 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 21:56 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 21:57 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 21:59 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:00 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:01 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:02 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:03 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:04 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:05 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:06 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:07 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:08 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:09 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:10 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:11 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:13 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:14 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:15 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:16 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:17 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:18 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/287#" title="Author self-approved">nlandolfi</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [nlandolfi]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:27 UTC, sebastienvas requested changes

2017-07-20 22:27 UTC, sebastienvas commented on prow/config.yaml
> +        - "--upload=gs://kubernetes-jenkins/logs"
Are you sure this is fine ? I don t think you need this.

2017-07-20 22:27 UTC, sebastienvas commented on prow/config.yaml
> +        - "--git-cache=/root/.cache/git"
What does git cache do ?

2017-07-20 22:31 UTC, nlandolfi commented on prow/config.yaml
> +        - "--git-cache=/root/.cache/git"
it caches the git repo so you may not need to pull all the objects again, but I mistakenly included the flag.

2017-07-20 22:31 UTC, nlandolfi commented on prow/config.yaml
> +        - "--upload=gs://kubernetes-jenkins/logs"
Definitely not -- my mistake. removed.

2017-07-20 22:46 UTC, yutongz commented
/lgtm

2017-07-20 22:49 UTC, sebastienvas approved these changes

2017-07-20 22:54 UTC, istio-testing commented
/test all [submit-queue is verifying that this PR is safe to merge]

2017-07-21 00:53 UTC, yutongz approved these changes

2017-07-21 15:01 UTC, istio-testing commented
/test all [submit-queue is verifying that this PR is safe to merge]

2017-07-21 15:08 UTC, yutongz commented
When you want get this pr merged, comment "/test all" to re-trigger test.

2017-07-21 16:07 UTC, nlandolfi commented
/test all

2017-07-21 16:09 UTC, istio-testing commented
Automatic merge from submit-queue

2017-07-21 16:09 UTC, merged

2017-07-21 16:09 UTC, istio-testing commented
@nlandolfi: I updated Prow config for you!.

<details>

In response to [this](https://github.com/istio/test-infra/pull/287):

>This introduces a `pilot-postsubmit` job.
>
>**Release note**:
>```release-note
>NONE
>```

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>