Update OWNERS file
istio/test-infra pull request #295
Opened 2017-07-20 21:51 UTC by yutongz

2017-07-20 21:51 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 21:52 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 21:53 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 21:54 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 21:55 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 21:56 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 21:57 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 21:58 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:00 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:00 UTC, nlandolfi requested changes

2017-07-20 22:00 UTC, nlandolfi commented on OWNERS
> +
nit: rm trailing new line?

2017-07-20 22:00 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:01 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:02 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:03 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:04 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:05 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:06 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:07 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:08 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:09 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:10 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:11 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:12 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:13 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:14 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:15 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:16 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:18 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:18 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio/test-infra/pull/295#" title="Author self-approved">yutongz</a>*

*No associated issue*. Update pull-request body to add a reference to an issue, or get approval with `/approve no-issue`

The full list of commands accepted by this bot can be found [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).

<details >
Needs approval from an approver in each of these OWNERS Files:

- ~~[OWNERS](https://github.com/istio/test-infra/blob/master/OWNERS)~~ [yutongz]

You can indicate your approval by writing `/approve` in a comment
You can cancel your approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2017-07-20 22:21 UTC, yutongz commented
PTAL

2017-07-20 22:51 UTC, sebastienvas approved these changes

2017-07-21 00:55 UTC, istio-testing commented
/test all [submit-queue is verifying that this PR is safe to merge]

2017-07-21 00:57 UTC, yutongz commented
/test all [submit-queue is verifying that this PR is safe to merge]

2017-07-21 00:59 UTC, istio-testing commented
Automatic merge from submit-queue

2017-07-21 00:59 UTC, merged