Prow: Adds crontab job for cluster cleanup
istio/test-infra pull request #297
Opened 2017-07-20 22:36 UTC by sebastienvas

2017-07-20 22:38 UTC, istio-testing commented
@sebastienvas: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
prow/test-infra-presubmit.sh | e7a90272b8ced2647b32fdc7cc7920c18256c6c0 | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_test-infra/297/test-infra-presubmit/74/) | `@istio-testing bazel test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-07-20 22:46 UTC, nlandolfi requested changes

2017-07-20 22:46 UTC, nlandolfi commented on prow/test-infra-cleanup-cluster.sh
> +if [ "${CI:-}" == 'bootstrap' ]; then
I think you can forego this if block here?

2017-07-20 22:46 UTC, nlandolfi commented
@istio-testing test this

2017-07-20 23:03 UTC, sebastienvas commented
PTAL

2017-07-21 04:57 UTC, nlandolfi approved these changes
LGTM

2017-07-21 15:28 UTC, yutongz commented
@nlandolfi try use /lgtm to add label for mungegithub, thanks :)

2017-07-21 15:39 UTC, yutongz commented
@sebastienvas Please refer to [pr template](https://raw.githubusercontent.com/kubernetes/kubernetes/master/.github/PULL_REQUEST_TEMPLATE.md) to add release note (We are not going to keep this feature in test-infra, just want you to dogfood it)

2017-07-21 16:09 UTC, nlandolfi commented
/release-note-none 
/lgtm

2017-07-21 16:10 UTC, istio-testing commented
@sebastienvas PR needs rebase

2017-07-21 16:10 UTC, nlandolfi commented
@sebastienvas looks like merge conflicts

2017-07-21 16:15 UTC, istio-testing commented
/lgtm cancel //PR changed after LGTM, removing LGTM. @nlandolfi @sebastienvas

2017-07-21 16:55 UTC, nlandolfi commented
/lgtm

2017-07-21 17:10 UTC, istio-testing commented
/test all [submit-queue is verifying that this PR is safe to merge]

2017-07-21 17:11 UTC, yutongz commented
/test all

2017-07-21 17:14 UTC, istio-testing commented
Automatic merge from submit-queue

2017-07-21 17:14 UTC, istio-testing commented
@sebastienvas: I updated Prow config for you!.

<details>

In response to [this](https://github.com/istio/test-infra/pull/297):

>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2017-07-21 17:14 UTC, merged