Upload TestGrid Config directly to GCS
istio/test-infra pull request #3534
Opened 2021-08-31 18:55 UTC by chases2

First step of #3533

/assign @cjwagner

2021-08-31 18:55 UTC, istio-testing commented
@chases2: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pull-test-infra-prow-checkconfig | cf1fc00a0d55729c996de5e991cc77d083ef6705 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_test-infra/3534/pull-test-infra-prow-checkconfig/1432779058956996608) | `/test pull-test-infra-prow-checkconfig`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-31 18:56 UTC, istio-testing commented
@chases2: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pull-test-infra-prow-checkconfig | cf1fc00a0d55729c996de5e991cc77d083ef6705 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_test-infra/3534/pull-test-infra-prow-checkconfig/1432779058956996608) | `/test pull-test-infra-prow-checkconfig`
lint_test-infra | cf1fc00a0d55729c996de5e991cc77d083ef6705 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_test-infra/3534/lint_test-infra/1432779058822778880) | `/test lint_test-infra`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-31 18:56 UTC, istio-testing commented
@chases2: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pull-test-infra-prow-checkconfig | cf1fc00a0d55729c996de5e991cc77d083ef6705 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_test-infra/3534/pull-test-infra-prow-checkconfig/1432779058956996608) | `/test pull-test-infra-prow-checkconfig`
lint_test-infra | cf1fc00a0d55729c996de5e991cc77d083ef6705 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_test-infra/3534/lint_test-infra/1432779058822778880) | `/test lint_test-infra`
pull-test-infra-check-testgrid-config | cf1fc00a0d55729c996de5e991cc77d083ef6705 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_test-infra/3534/pull-test-infra-check-testgrid-config/1432779058923442176) | `/test pull-test-infra-check-testgrid-config`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-31 18:58 UTC, istio-testing commented
@chases2: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pull-test-infra-prow-checkconfig | cf1fc00a0d55729c996de5e991cc77d083ef6705 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_test-infra/3534/pull-test-infra-prow-checkconfig/1432779058956996608) | `/test pull-test-infra-prow-checkconfig`
lint_test-infra | cf1fc00a0d55729c996de5e991cc77d083ef6705 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_test-infra/3534/lint_test-infra/1432779058822778880) | `/test lint_test-infra`
pull-test-infra-check-testgrid-config | cf1fc00a0d55729c996de5e991cc77d083ef6705 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_test-infra/3534/pull-test-infra-check-testgrid-config/1432779058923442176) | `/test pull-test-infra-check-testgrid-config`
test_test-infra | cf1fc00a0d55729c996de5e991cc77d083ef6705 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_test-infra/3534/test_test-infra/1432779058860527616) | `/test test_test-infra`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-31 23:32 UTC, chaodaiG requested changes

2021-08-31 23:32 UTC, chaodaiG commented on testgrid/default.yaml
> +    url: https://prow.k8s.io/job-history/<gcs_prefix>
should this be prow.istio.io?

2021-08-31 23:32 UTC, chaodaiG commented on testgrid/default.yaml
> +    url: https://prow.k8s.io/view/gs/<gcs_prefix>/<changelist>
same prow.istio.io

2021-09-01 16:30 UTC, chases2 commented on testgrid/default.yaml
> +    url: https://prow.k8s.io/job-history/<gcs_prefix>
Good catch! Fixed

2021-09-01 17:02 UTC, chaodaiG approved these changes

2021-09-01 17:29 UTC, howardjohn approved these changes

2021-09-01 17:32 UTC, merged

2021-09-01 17:32 UTC, istio-testing commented
@chases2: Updated the `job-config` configmap in namespace `default` at cluster `default` using the following files:
 - key `istio.test-infra.master.yaml` using file `prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml`
 - key `istio.test-infra.trusted.master.yaml` using file `prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml`

<details>

In response to [this](https://github.com/istio/test-infra/pull/3534):

>First step of #3533
>
>/assign @cjwagner 


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>