Dockerfile and build configs for the GCB build container
istio/test-infra pull request #405
Opened 2017-08-22 23:02 UTC by rvkubiak

**Release note**:
```release-note
```

2017-08-23 03:47 UTC, sebastienvas requested changes
Could you please move this under the docker directory,

2017-08-23 18:28 UTC, rvkubiak commented
Moved

2017-08-24 04:34 UTC, sebastienvas commented
/lgtm

2017-08-24 04:34 UTC, sebastienvas approved these changes

2017-08-26 20:25 UTC, merged