Separate code coverage from presubmit for pilot
istio/test-infra pull request #422
Opened 2017-08-27 02:21 UTC by yutongz

**Release note**:

```release-note
none
```

2017-08-27 02:25 UTC, yutongz commented
/assign @sebastienvas

2017-08-27 03:42 UTC, sebastienvas commented
Could you please update the description and give a reason for splitting this?

Also you might want to do this in 2 steps, ie leave the presubmit the way it is such that you don't break it once you push this, split the presubmit on pilot and then, update the config to remove codecov.

2017-08-27 03:53 UTC, sebastienvas commented
/lgtm

2017-08-27 06:23 UTC, yutongz commented
I safely remove the "code coverage" part from istio/pilot prow/pilot-presubmit.sh, so I think as long as we merge that pr first, we can keep pilot presubmit green. And I mute pilot-coverage job for now.

P.S. It seems when you "github approve" [pr in pilot](https://github.com/istio/pilot/pull/1110#pullrequestreview-58814741), prow add "lgtm" on this pr since I referred that pr. It's fun and kind of smart, but a bit of confusing. I am recording it.

2017-08-30 07:21 UTC, yutongz commented
/approve

2017-08-30 07:22 UTC, yutongz commented
/approve cancel

2017-08-30 20:12 UTC, sebastienvas approved these changes

2017-08-30 20:13 UTC, sebastienvas requested changes
Actually are you doing another presubmti or another after_success

2017-08-30 20:27 UTC, yutongz commented
Another after success, e2e doesn't depend on code coverage so they can work concurrently.

2017-08-30 23:09 UTC, sebastienvas commented
/lgtm

2017-08-30 23:09 UTC, sebastienvas approved these changes

2017-08-31 04:16 UTC, yutongz commented
/test test-infra-presubmit

2017-08-31 04:42 UTC, yutongz commented
hi robot

2017-08-31 04:45 UTC, merged

2017-08-31 04:45 UTC, istio-testing commented
@yutongz: I updated Prow config for you!.

<details>

In response to [this](https://github.com/istio/test-infra/pull/422):

>Separate coverage processes (codecov.io, package check) with presubmit:
>    1) Speed up presubmit
>    2) Coverage will not block presubmit, we can easily make it required or not.
>
>**Release note**:
><!--  Steps to write your release note:
>1. Use the release-note-* labels to set the release note state (if you have access)
>2. Enter your extended release note in the below block; leaving it blank means using the PR title as the release note. If no release note is required, just write `NONE`.
>-->
>```release-note
>none
>```
>Connect to https://github.com/istio/pilot/pull/1110

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>