Create generate-deps-configmaps tool
istio/test-infra pull request #5186
Opened 2024-01-31 18:32 UTC by dhawton

The purpose of this script is to generate the istio-deps and release-deps configmaps (and any other we may need in the future) that are needed for istio-private work.

Currently these are not generated and are caught after-the-fact when the PSWG team is building security releases when jobs in Prow fail to schedule since the ConfigMaps are missing. We should, ideally, have this as part of the branch cutting process. Cleanup will still be manual, but can occur during the regular EOL cleanup flow.

After merging, the last step is to update the release branch cutting issue template to ensure this is completed during Step 3.

Closes #5184

2024-01-31 21:07 UTC, ilrudie requested changes
over all looks helpful, couple of suggestions and 1 issue with python happily allowing you to use an uninitialized variable which results in outputting a mangled file on the non-`--dry-run` codepath...

2024-01-31 21:07 UTC, ilrudie commented on tools/generate-deps-configmaps/README.md
> +The following is a list of supported options. If an option is optional, than its _default_ value will be used if not provided. If an option is required
sp.
```suggestion
The following is a list of supported options. If an option is optional, then its _default_ value will be used if not provided. If an option is required
```

2024-01-31 21:07 UTC, ilrudie commented on tools/generate-deps-configmaps/README.md
> +The templates utilize [Template strings](https://docs.python.org/3.4/library/string.html#template-strings) to generate the ConfigMap dependency data.
Any reason we point to 3.4 when we're asking for a 3.6+ prereq?

2024-01-31 21:07 UTC, ilrudie commented on tools/generate-deps-configmaps/generate.py
> +    extension = ".template"
convey intent that this is meant to be constant. no practical effect to the code though so feel free to disregard
```suggestion
    EXTENSION = ".template"
```

2024-01-31 21:07 UTC, ilrudie commented on tools/generate-deps-configmaps/generate.py
> +            generate_yaml(cm, stream)
```suggestion
            generate_yaml(release_deps, stream)
```

2024-01-31 21:08 UTC, dhawton commented on tools/generate-deps-configmaps/README.md
> +The templates utilize [Template strings](https://docs.python.org/3.4/library/string.html#template-strings) to generate the ConfigMap dependency data.
```suggestion
The templates utilize [Template strings](https://docs.python.org/3.6/library/string.html#template-strings) to generate the ConfigMap dependency data.
```

2024-01-31 21:28 UTC, ilrudie requested changes
this one's on me, my "convey that this is a const" suggestion should not have been accepted as is... it broke things. I didn't make that at all clear in my comment though

2024-01-31 21:28 UTC, ilrudie commented on tools/generate-deps-configmaps/generate.py
> +                templates.append(file.replace(extension, ""))
sorry, the previous suggestion was a partial which breaks things if accepted as it was. that's on me
```suggestion
            if file.endswith(EXTENSION):
                templates.append(file.replace(EXTENSION, ""))
```

2024-01-31 21:35 UTC, ilrudie commented
A bit of an aside: Do we have any lint/formatting requirements for python? in other python project I contribute to [black](https://pypi.org/project/black/) is required. I'm really not an expert on python TBH but I think if we're going to have some python kicking around then introducing black to our linting is probably a good shout.

2024-01-31 21:38 UTC, dhawton commented
> A bit of an aside: Do we have any lint/formatting requirements for python? in other python project I contribute to [black](https://pypi.org/project/black/) is required. I'm really not an expert on python TBH but I think if we're going to have some python kicking around then introducing black to our linting is probably a good shout.
> 
> I don't think it's required for this to merge (IMO at least) but I would say maybe run black against your code and commit the results.
> 
> Also maybe we should open an issue to track/consider adding black formatter.

We use autopep8 to apply the pep 8 styling against it.

2024-01-31 21:41 UTC, ilrudie commented
> > A bit of an aside: Do we have any lint/formatting requirements for python? in other python project I contribute to [black](https://pypi.org/project/black/) is required. I'm really not an expert on python TBH but I think if we're going to have some python kicking around then introducing black to our linting is probably a good shout.
> > I don't think it's required for this to merge (IMO at least) but I would say maybe run black against your code and commit the results.
> > Also maybe we should open an issue to track/consider adding black formatter.
> 
> We use autopep8 to apply the pep 8 styling against it.

I was not aware of autopep8... thanks for the info and disregard previous comment then

2024-01-31 22:15 UTC, ilrudie commented
Side note... this script strips out the comments at the top of the yaml file I think. Might not be a big deal but something to consider

2024-01-31 22:25 UTC, ilrudie approved these changes
Potential issue with the yaml comments aside, this seems fit for purpose. All error handling isn't perfect but I don't think the imperfect error handling is dangerous and using this seems less error prone than manually adjusting the yaml.

2024-01-31 23:01 UTC, ilrudie commented
well, you can strike my comment about error handling now 😄

2024-02-26 19:46 UTC, ericvn approved these changes

2024-02-27 22:04 UTC, istio-testing commented
PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2024-02-28 00:08 UTC, merged