change envoy UPDATE_BRANCH to 1.30 for 1.23
istio/test-infra pull request #5436
Opened 2024-07-17 05:16 UTC by thedebugger

2024-07-17 05:18 UTC, istio-testing commented
@thedebugger: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
gencheck_test-infra | f8b48d6ea5749e514789c5bcaecf1e09ee13be4b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_test-infra/5436/gencheck_test-infra/1813442771319525376) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-07-17 14:15 UTC, howardjohn approved these changes

2024-07-17 14:21 UTC, dhawton commented
Istio 1.23 should be Envoy 1.31, right? 1.22 was 1.30.. and we typically +1 both. Right now the main branch is 1.31?

2024-07-17 15:50 UTC, dhawton requested changes
Leave on main until they cut 1.31.

2024-07-17 16:55 UTC, mikemorris requested changes
We'll stay on Envoy `main` branch until 1.31 is published. Suggesting changes and blocking until https://github.com/envoyproxy/envoy/pull/35188 is complete.

2024-07-17 16:55 UTC, mikemorris commented on prow/cluster/jobs/istio/proxy/istio.proxy.release-1.23.gen.yaml
> +      - --cmd=UPDATE_BRANCH=release/v1.30 scripts/update_envoy.sh
```suggestion
      - --cmd=UPDATE_BRANCH=release/v1.31 scripts/update_envoy.sh
```

2024-07-17 16:55 UTC, mikemorris commented on prow/config/jobs/proxy-1.23.yaml
> +  - --cmd=UPDATE_BRANCH=release/1.30 scripts/update_envoy.sh
```suggestion
  - --cmd=UPDATE_BRANCH=release/1.31 scripts/update_envoy.sh
```

2024-07-17 20:00 UTC, istio-testing commented
@thedebugger: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
gencheck_test-infra | 80f12bbac0977e66379b0ba0247106467d0a0141 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_test-infra/5436/gencheck_test-infra/1813664324439248896) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-07-23 15:37 UTC, mikemorris approved these changes

2024-07-24 01:57 UTC, zirain commented
https://github.com/envoyproxy/envoy/releases/tag/v1.31.0 is out, good to go!

2024-07-24 01:57 UTC, kfaseela approved these changes

2024-07-24 01:59 UTC, dhawton approved these changes

2024-07-24 02:03 UTC, merged

2024-07-24 02:03 UTC, istio-testing commented
@thedebugger: Updated the `job-config` configmap in namespace `default` at cluster `default` using the following files:
 - key `istio.proxy.release-1.23.gen.yaml` using file `prow/cluster/jobs/istio/proxy/istio.proxy.release-1.23.gen.yaml`

<details>

In response to [this](https://github.com/istio/test-infra/pull/5436):

>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository.
</details>